export const pricingData = [
    {
        id: 1,
        isPopular: false,
        planName: "Starter Package",
        description: "Perfect for small businesses and startups looking for professional design.",
        price: 799,
        billingFrequency: "/project",
        features: [
            "Logo Design & Branding",
            "Business Card Design",
            "2 Revision Rounds",
            "48hr Turnaround",
        ],
        buttonText: "Get Started",
    },
    {
        id: 2,
        isPopular: true,
        isExclusive: false,
        planName: "Professional Package",
        description: "Comprehensive design solutions for growing businesses.",
        price: 2499,
        billingFrequency: "/project",
        features: [
            "Complete Brand Identity",
            "Website Design (5 pages)",
            "Social Media Kit",
            "Unlimited Revisions",
            "Priority Support",
        ],
        buttonText: "Get Started",
    },
    {
        id: 3,
        isPopular: false,
        isExclusive: true,
        planName: "Enterprise Package",
        description: "Full-scale design partnership for established companies.",
        price: 5999,
        billingFrequency: "/month",
        features: [
            "Dedicated Design Team",
            "Unlimited Design Requests",
            "Brand Guidelines",
            "Monthly Strategy Sessions",
            "24/7 Priority Support",
        ],
        buttonText: "Contact Us",
    },
];